apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-auth-app
  template:
    metadata:
      labels:
        app: flask-auth-app
    spec:
      containers:
        - name: flask-auth-container
          image: flask-auth-app:latest   # Updated image name
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-auth-service
spec:
  selector:
    app: flask-auth-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort